### PR TITLE
Remove old and unused modules

### PR DESCRIPTION
**Pull request by fordnox**
Use hubot-scripts instead of copy in scripts

Some scripts are still left.

@ton31337

### CODE REVIEW

**Comment by ton31337** [comment]
will other scripts be used in an old way?

**Comment by ton31337** [comment]
:+1:

**Comment by fordnox** [comment]
There are these scripts left.
```
scripts/github-pubsub-pulls.coffee
scripts/github-pubsub-pushes.coffee
scripts/github-wiki.coffee
scripts/hubot-jenkins-notifier-pubsub.coffee
scripts/jenkins-pubsub-notifier.coffee
scripts/notifier.coffee
```

i know that i can remove `notifier.coffee` and `github-wiki.coffee` but i am not sure about others

i think we still use them?

**Comment by ton31337** [comment]
yeah, it's not a problem to keep them as they are ;-)

**Pull request merged**
